language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
before_script:
    - travis_retry composer self-update
script:
    - composer validate --strict
    - composer update --no-interaction --prefer-lowest
    - composer dumpautoload -o
    - vendor/bin/phpcs --standard=psr2 src/
    - vendor/bin/phpcs --standard=psr2 tests/
    - vendor/bin/phpunit
    - pip install --user codecov
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - php vendor/bin/codacycoverage clover build/logs/clover.xml
