language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
    - nightly
before_script:
    - composer self-update
    - composer validate --strict
    - composer update --no-interaction --prefer-lowest
    - composer dumpautoload -o
    - vendor/bin/phpcs --standard=psr2 src/
    - vendor/bin/phpcs --standard=psr2 tests/
    - vendor/bin/phpunit
    - pip install --user codecov
script: vendor/bin/phpunit -c test/phpunit.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - php vendor/bin/codacycoverage clover test/code_coverage/clover.xml
